version: '3'

services:
  database:
    build:
      context: ./docker-containers/database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    restart: on-failure

  php:
    build:
      context: ./docker-containers/php-fpm
    volumes:
      - ./phpfunctions:/var/www/phpfunctions:cached
      - ~/ssh/id_rsa:/root/.ssh/id_rsa
      - ./docker-containers/php-fpm/php-ini-local.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    restart: on-failure

  nginx:
    build:
      context: ./docker-containers/nginx
    volumes:
      - ./phpfunctions:/var/www/phpfunctions:cached
      - ./docker-containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-containers/nginx/sites:/etc/nginx/sites-available
      - ./docker-containers/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
      - database
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
