knpu_oauth2_client:
    clients:
        # will create a service: "knpu.oauth2.client.github"
        github:
            type: github
            client_id: '%env(OAUTH_GITHUB_ID)%'
            client_secret: '%env(OAUTH_GITHUB_SECRET)%'
            # the route that you're redirected to after
            redirect_route: connect_github_check
            redirect_params: {}